config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "flats#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <% @flats.each do |flat| %>
    <div class="card">
      <img src="https://images.unsplash.com/photo-1568605114967-8130f3a36994?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt="" class="card-img-top">
      <div class="card-body p-3">
        <h3 class="card-title"><%= flat.name %></h3>
        <p><%= flat.address %></p>
        <div class="d-flex flex-row space-between">
        <span><i class="fa-solid fa-people-roof"></i> <%= flat.number_of_guests %></span>
        <span><i class="fa-solid fa-euro-sign"></i> <%= flat.price_per_night %></span>
        </div>
      </div>
      <div class="card-footer p-3">
      <%= link_to "more info", flat_path(flat), class: "card-link text-decoration-none" %>
      <%= link_to "edit", flat_path(flat), class: "card-link text-decoration-none text-warning" %>
      <%= link_to "remove", flat_path(flat), class: "card-link text-decoration-none text-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div class="row">
<div class="col-8">
  <div class="card">
  <h3 class="card-title"><%= @flat.name %></h3>
  <p><%= @flat.address %></p>
  </div>
  <div class="card">
  <p><%= @flat.description %></p>
  </div>
</div>
<div class="col-4">

</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar p-2">
    <span>Simple Airbnb</span>
    <%= link_to "add new flat", new_flat_path, class: "btn btn-outline-primary" %>
  </nav>
    <%= yield %>
  </body>
</html>